name: Reusable Workflow Caller Demo

on:
  # workflow_dispatch is a manually invoked workflow
  workflow_dispatch:

jobs:
  reusable-workflow-caller-1A:
    name: 01A Calling Reusable Workflow
    # Use the `uses` keyword to invoke Reusable GitHub Workflows
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    secrets: inherit
